### ISSUE TITLE
[question/discussion] how does trollduction differ from other orchestration frameworks?

### ISSUE THREAD

**Issue by 7yl4r** [pytroll/trollduction#21]
I am in early stages of developing a processing pipeline and have no experience with pytroll so please forgive my ignorance, but I am wondering how trollduction differs from a more generic orchestration framework like ariflow or luigi. 

Does trollduction do something differently, better, or specific to this application domain? 

Or, posed another way: What obstacles might I encounter trying to orchestrate pytroll-based processing with airflow that I would not encounter if using trollduction?

These were my thoughts while browsing the docs, and it may be a topic worth addressing there.

**Comment by mraspaud** [comment]
@7yl4r Very good questions indeed !

I'm not really familiar with the frameworks you mention, but I would say that trollduction is more specific to this application domain. Here, we often need to read a bunch of weather satellite data, resample (reproject) it and then generate a lot of images. We do all of this in memory in order to speed up things, while at the same time trying not to have too much data in memory at the same time. From what I understand, in generic workflows, everything would be based on files, which is fine but would slow us down. Well at least that's my view :)

**Comment by pnuu** [comment]
From the [airflow](https://github.com/apache/incubator-airflow) GitHub page:
> Airflow is not a data streaming solution. Tasks do not move data from one to the other (though tasks can exchange metadata!).

As @mraspaud pointed out, in satellite processing we need to handle quite a lot of data and pass it from one processing stage to another. As trollduction grew to support more use cases on weather satellite data processing, it also grew very cluttered in and hard to maintain. The current preferred solution is [trollflow](https://github.com/pytroll/trollflow) with the satellite-specific plug-ins in [trollflow-sat](https://github.com/pytroll/trollflow-sat). Trollflow still needs cleanup and documentation (practically only documentation are the example configs in trollflow-sat), but it is already in operational use at couple of national meteorological services. And more are joining :-)

**Comment by 7yl4r** [comment]
I didn't realize trollduction passes objects in RAM, that's a nice feature for sure, and I'll have to take a look at trollflow and trollflow-sat.

Thanks for clarifying!
